### ISSUE TITLE
RuntimeError: Cannot initialize CUDA without ATen_cuda library. 

### ISSUE THREAD

**Issue by 1158755456** [svip-lab/GazeFollowing#7]
(pytorch) D:\Projects\Pycharm2019Projects\GazeFollow\code>python inference.py ../images/00000003.jpg 0.52 0.14
Traceback (most recent call last):
  File "inference.py", line 152, in <module>
    main()
  File "inference.py", line 134, in main
    net.cuda()
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 191, in _apply
    param.data = fn(param.data)
  File "D:\IDE\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this erro
r has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA l
ibrary MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link argument
s; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on
 your binary to see if there is a dependency on *_cuda.so library.

**Comment by niujinshuchong** [comment]
Hi, it seems that you need a gpu to run the code. 

Or you can change the code to support cpu inference.

**Comment by 1158755456** [comment]
> 嗨，看来您需要一个GPU来运行代码。
> 
> 或者，您可以更改代码以支持cpu推理。

ok thanks
